[package]
name = "program_duration"
version = "0.1.0"
authors = ["Lars Tobias Skjong-Børsting <larstobi@relatime.no>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
serde = { version = "1.0.101", features = ["derive"] }
serde_yaml = "0.8.9"
serde_derive = "1.0.101"
yaml-rust = "0.4.3"
